events {
    worker_connections 1024;
}

http {
    upstream backend {
        server gusto-backend:8000;
    }

    upstream admin {
        server gusto-admin:80;
    }

    server {
        listen 80;
        server_name _;

        location /api {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://admin;
            proxy_set_header Host $host;
        }
    }
}
